events {
    worker_connections 1024;
}

http {
    upstream users_backend {
        server service_users1:8001 max_fails=2 fail_timeout=30s;
        server service_users2:8002 max_fails=2 fail_timeout=30s;
    }

    upstream orders_backend {
        server service_orders1:8003 max_fails=2 fail_timeout=30s;
        server service_orders2:8004 max_fails=2 fail_timeout=30s;
    }

    server {
        listen 80;

        location /users {
            proxy_pass http://users_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /orders {
            proxy_pass http://orders_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}